- name: MicroK8s Installation
  hosts: all
  become: yes  # If you need to escalate privileges to run the script

  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost

    - name: Ensure the SSH key is in authorized_keys
      authorized_key:
        user: jenkins
        state: present
        key: "{{ lookup('file', '/var/lib/jenkins/.ssh/id_rsa.pub') }}"

    - name: Install the MicroK8s
      shell: |
        # Install microk8s
        echo "Inside snap install"
        sudo snap install microk8s --classic || echo "Already Installed"
        echo "Wait for microk8s to be ready"
        sudo microk8s status --wait-ready

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Wait for apt lock    # Corrected the indentation here
      command: sh -c 'while lsof /var/lib/dpkg/lock-frontend; do sleep 10; done'

    - name: Copy nginx reverse proxy config for SonarQube
      copy:
        src: nginx-sonar-config.conf
        dest: /etc/nginx/sites-available/sonar

    - name: Enable nginx config
      file:
        src: /etc/nginx/sites-available/sonar
        dest: /etc/nginx/sites-enabled/sonar
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
