---
- name: MicroK8s Installation
  hosts: EC2
  become: yes  # If you need to escalate privileges to run the script

  tasks:
    - name: Install the MicroK8s
      shell: |
        # Install microk8s
        echo "Inside snap install"
        
        sudo snap install microk8s --classic || echo "Already Installed"

        echo "Wait for microk8s to be ready"
        sudo microk8s status --wait-ready
