- name: MicroK8s Installation
  hosts: all
  become: yes
  vars:
    nginx_config_template: nginx-sonar-config.conf.j2
    nginx_config_output: /etc/nginx/sites-available/sonar

  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost

    - name: Ensure the SSH key is in authorized_keys
      authorized_key:
        user: jenkins
        state: present
        key: "{{ lookup('file', '/var/lib/jenkins/.ssh/id_rsa.pub') }}"

    - name: Install the MicroK8s
      shell: |
        sudo snap install microk8s --classic || echo "Already Installed"
        sudo microk8s status --wait-ready

    - name: Forcefully remove apt locks
      command: rm -f /var/lib/dpkg/lock-frontend /var/cache/apt/archives/lock
      changed_when: false

    - name: Kill any apt processes
      shell: pkill -9 apt || true
      changed_when: false

    - name: Check if dpkg needs configuration
      shell: dpkg --configure -a
      register: dpkg_check
      changed_when: false
      failed_when: false

    - name: Correct dpkg configuration if needed
      command: dpkg --configure -a
      when: "'dpkg was interrupted' in dpkg_check.stderr"

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Fetch EC2 public IP
      command: curl -s http://169.254.169.254/latest/meta-data/public-ipv4
      register: ec2_public_ip
      changed_when: false

    - name: Copy nginx reverse proxy config for SonarQube
      template:
        src: "{{ nginx_config_template }}"
        dest: "{{ nginx_config_output }}"
        mode: '0644'
      vars:
        public_ip: "{{ ec2_public_ip.stdout }}"

    - name: Enable nginx config
      file:
        src: "{{ nginx_config_output }}"
        dest: /etc/nginx/sites-enabled/sonar
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
