- name: MicroK8s Installation
  hosts: all
  become: yes

  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost

    - name: Ensure the SSH key is in authorized_keys
      authorized_key:
        user: jenkins
        state: present
        key: "{{ lookup('file', '/var/lib/jenkins/.ssh/id_rsa.pub') }}"

    - name: Install the MicroK8s
      shell: |
        sudo snap install microk8s --classic || echo "Already Installed"
        sudo microk8s status --wait-ready

    - name: Forcefully remove apt locks
      command: rm -f /var/lib/dpkg/lock-frontend /var/cache/apt/archives/lock
      changed_when: false

    - name: Kill any apt processes
      shell: pkill -9 apt || true
      changed_when: false

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Copy nginx reverse proxy config for SonarQube
      copy:
        src: nginx-sonar-config.conf
        dest: /etc/nginx/sites-available/sonar

    - name: Enable nginx config
      file:
        src: /etc/nginx/sites-available/sonar
        dest: /etc/nginx/sites-enabled/sonar
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
