# sonarqube/values.yaml

sonarqube:
  image:
    repository: sonarqube
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1  

service:
  type: LoadBalancer
  port: 80

ingressEnabled: true
