pipeline {
    agent any

    environment {
        WORKSPACE_DIR = "${env.WORKSPACE}" // Use Jenkins workspace
    }

    stages {
        stage('Initialization') {
            steps {
                // Clean Jenkins workspace
                cleanWs()
                
                // Clone the repository
                sh 'git clone https://github.com/zinougeh/zino_sec_comp_take_home.git'
            }
        }

        stage('Setup SSH') {
            steps {
                script {
                    def sshDir = "${WORKSPACE_DIR}/.ssh"
                    if (!fileExists(sshDir)) {
                        sh "mkdir -p ${sshDir}"
                    }
                    if(!fileExists("${sshDir}/id_rsa.pub")) {
                        sh "ssh-keygen -t rsa -b 4096 -f ${sshDir}/id_rsa -N ''"
                        env.SSH_PUBLIC_KEY = sh(script: "cat ${sshDir}/id_rsa.pub", returnStdout: true).trim()
                    } else {
                        env.SSH_PUBLIC_KEY = sh(script: "cat ${sshDir}/id_rsa.pub", returnStdout: true).trim()
                    }
                }
            }
        }

        stage('Deploy on AWS') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS_Access']]) {
                    dir('zino_sec_comp_take_home/task1/terraform') {
                        sh 'terraform init'
                        sh "terraform apply -var 'ssh_public_key=${SSH_PUBLIC_KEY}' -auto-approve"
                        sleep time: 200, unit: 'SECONDS'
                        script {
                            env.EC2_PUBLIC_IP = sh(script: 'terraform output instance_public_ip', returnStdout: true).trim()
                        }
                    }
                }
            }
        }

        stage('Configure EC2 with MicroK8s') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWS_Access']]) {
                    dir('zino_sec_comp_take_home/task1/microk8s/') {
                        script {
                            def inventoryFile = """
                                [EC2]
                                ${EC2_PUBLIC_IP}
                            """
                            writeFile file: 'temp_inventory.ini', text: inventoryFile
                        }
                        sshagent(credentials: ['sec_com_ass_key_pair']) {
                            sh 'cat temp_inventory.ini'
                            sh 'export ANSIBLE_HOST_KEY_CHECKING=False'
                            sh "ansible-playbook ansible.yml -i temp_inventory.ini --private-key=${WORKSPACE_DIR}/.ssh/id_rsa -u ubuntu"
                        }
                    }
                }
            }
        }

        stage('Deploy SonarQube') {
            steps {
                dir('zino_sec_comp_take_home/task1/sonar/') {
                    sleep time: 60, unit: 'SECONDS'
                    sshagent(credentials: ['sec_com_ass_key_pair']) {
                        sh "scp -o StrictHostKeyChecking=no -r sonarqube ubuntu@${EC2_PUBLIC_IP}:/tmp"
                        sh "ssh -o StrictHostKeyChecking=no ubuntu@${EC2_PUBLIC_IP} 'sudo microk8s helm install sonar /tmp/sonarqube && sudo microk8s helm ls'"
                    }
                }
            }
        }
    }
}
