# sonarqube/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deploy
  labels:
    app: sonar
spec:
  replicas: {{ .Values.sonarqube.replicaCount }}
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.sonarqube.image.repository }}:{{ .Values.sonarqube.image.tag }}"
          imagePullPolicy: {{ .Values.sonarqube.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
