# sonarqube/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  labels:
    app: sonar
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 30080
  selector:
    app: sonar
